In [ ]:
#statistics and probability
 #based on statistics with code krish

In [5]:
import seaborn as sn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import statistics

In [4]:
# mean median mode

In [6]:
df=pd.read_csv("C:\\Users\\vedan\\Downloads\\datasets\\cars.csv")

In [7]:
df.head()

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [8]:
np.mean(df['Volume'])

np.float64(1611.111111111111)

In [9]:
np.median(df['Volume'])

np.float64(1600.0)

In [10]:
statistics.mode(df['Volume'])

1600

In [13]:
sn.boxplot(df['CO2'])

In [16]:
sn.histplot(df['Volume'],kde=True)

In [17]:
df1=pd.read_csv("C:\\Users\\vedan\\Downloads\\datasets\\Iris.csv")

In [18]:
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
sn.histplot(df1['SepalWidthCm'],kde=True)

In [20]:
sn.countplot(df1['Species'])

In [21]:
np.percentile(df1['SepalLengthCm'],[25,75])

array([5.1, 6.4])