In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"E:\dynamic_supply_chain_logistics_dataset.csv")

In [3]:
df.head(10)

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
0,2021-01-01 00:00:00,40.375568,-77.014318,5.136512,4.998009,5.927586,985.716862,4.951392,0.481294,0.761166,...,0.574400,0.777263,1.182116,0.502006,0.033843,0.978599,0.506152,0.885291,Moderate Risk,9.110682
1,2021-01-01 01:00:00,33.507818,-117.036902,5.101512,0.984929,1.591992,396.700206,1.030379,0.620780,0.196594,...,-9.753493,0.091839,9.611988,0.966774,0.201725,0.918586,0.980784,0.544178,High Risk,8.175281
2,2021-01-01 02:00:00,30.020640,-75.269224,5.090803,4.972665,8.787765,832.408935,4.220229,0.810933,0.152742,...,-6.491034,0.253529,6.570431,0.945627,0.264045,0.394215,0.998633,0.803322,High Risk,1.283594
3,2021-01-01 03:00:00,36.649223,-70.190529,8.219558,3.095064,0.045257,0.573283,0.530186,0.008525,0.811885,...,-0.151276,0.877576,0.548952,4.674035,0.362885,0.905444,0.993320,0.025977,High Risk,9.304897
4,2021-01-01 04:00:00,30.001279,-70.012195,5.000075,3.216077,8.004851,914.925067,3.620890,0.020083,0.053659,...,2.429448,0.262081,8.861443,3.445429,0.016957,0.258702,0.912433,0.991122,High Risk,7.752484
5,2021-01-01 05:00:00,47.864549,-119.998386,5.533563,4.862386,0.499405,822.590649,0.768521,0.062074,0.397323,...,11.301343,0.041378,9.492603,2.163846,0.183964,0.978620,0.838287,0.982023,High Risk,-1.630307
6,2021-01-01 06:00:00,33.846390,-95.940118,5.779804,4.999979,8.750501,6.048354,3.923828,0.333237,0.002689,...,-9.076670,0.243348,9.870430,4.159665,0.020699,0.986597,0.999357,0.061457,High Risk,5.135374
7,2021-01-01 07:00:00,32.601885,-102.316635,5.474695,0.375511,4.813078,256.293208,2.352963,0.021812,0.240859,...,36.838728,0.344496,2.954216,1.456898,0.012490,0.185078,0.514001,0.979538,Moderate Risk,7.432758
8,2021-01-01 08:00:00,39.787194,-90.897918,5.680607,4.958875,9.613161,109.816868,0.592249,0.049304,0.183048,...,-9.999960,0.914129,7.158868,2.169863,0.876879,0.996431,0.321267,0.223533,Moderate Risk,1.323351
9,2021-01-01 09:00:00,47.728499,-113.413561,5.088425,1.508709,9.897407,0.032110,0.781215,0.069873,0.744814,...,-10.000000,0.032444,3.587067,3.751473,0.011959,0.453395,0.996365,0.233778,High Risk,0.739935

In [4]:
df.tail(10)

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
32055,2024-08-28 15:00:00,43.711808,-70.683791,19.025349,4.843913,5.431285,14.217233,0.512915,0.020993,0.999999,...,-9.638218,0.034525,7.680671,3.126804,0.437310,0.999268,0.982090,0.999592,High Risk,-1.961849
32056,2024-08-28 16:00:00,30.000969,-111.308105,11.652603,4.734567,0.009986,708.119829,4.237292,0.855450,0.178631,...,8.934973,0.049812,4.560110,2.086461,0.300402,0.998272,0.955927,0.977303,High Risk,6.832222
32057,2024-08-28 17:00:00,48.014536,-77.195743,11.876074,1.246200,5.455419,25.572915,1.002963,0.734786,0.757929,...,-9.999998,0.721237,6.137359,1.396913,0.000843,0.125209,0.097382,0.000500,Low Risk,-0.294438
32058,2024-08-28 18:00:00,31.736047,-105.043698,7.302981,1.530296,8.684132,611.009295,1.536364,0.243316,0.568838,...,-9.876607,0.000680,8.651963,2.493017,0.185740,0.247039,0.961499,0.099892,High Risk,9.439812
32059,2024-08-28 19:00:00,36.064390,-77.514767,5.144438,4.655563,1.366022,90.673960,4.908962,0.996305,0.316066,...,-7.428483,0.764472,9.958613,0.506066,0.494014,0.999445,0.123199,0.016340,Low Risk,9.920693
32060,2024-08-28 20:00:00,48.496665,-104.031158,5.421806,4.394370,0.192421,127.684977,3.607803,0.208643,0.992997,...,-8.835069,0.199377,9.893402,0.966050,0.109571,0.511074,0.953467,0.916745,High Risk,5.506049
32061,2024-08-28 21:00:00,34.670137,-89.893091,10.624778,2.700635,8.736143,84.638889,1.218165,0.472389,0.946031,...,-2.517654,0.673775,0.854378,1.665889,0.530289,0.868418,0.995329,0.808963,High Risk,-1.876938
32062,2024-08-28 22:00:00,42.963338,-82.149873,5.071596,0.485288,7.420200,48.500920,4.999149,0.064366,0.437687,...,29.410878,0.949644,4.480552,0.690990,0.537100,0.896798,0.442299,0.959197,Moderate Risk,9.790219
32063,2024-08-28 23:00:00,32.082410,-70.070154,5.000000,4.759411,0.932050,972.437425,0.505242,0.250949,0.517051,...,-6.951137,0.407377,9.185549,4.462204,0.012896,0.463018,0.999999,0.557340,High Risk,9.956879
32064,2024-08-29 00:00:00,38.576482,-94.579542,5.000046,4.068440,7.156608,16.669708,2.207746,0.486014,0.985761,...,18.796515,0.876529,2.112655,2.118384,0.974045,0.759489,0.996928,0.999230,High Risk,2.099656

In [5]:
df.isnull()

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32060,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32061,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32062,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32063,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32064,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
total=df.isnull().sum()

In [7]:
total

timestamp                          0
vehicle_gps_latitude               0
vehicle_gps_longitude              0
fuel_consumption_rate              0
eta_variation_hours                0
traffic_congestion_level           0
warehouse_inventory_level          0
loading_unloading_time             0
handling_equipment_availability    0
order_fulfillment_status           0
weather_condition_severity         0
port_congestion_level              0
shipping_costs                     0
supplier_reliability_score         0
lead_time_days                     0
historical_demand                  0
iot_temperature                    0
cargo_condition_status             0
route_risk_level                   0
customs_clearance_time             0
driver_behavior_score              0
fatigue_monitoring_score           0
disruption_likelihood_score        0
delay_probability                  0
risk_classification                0
delivery_time_deviation            0
dtype: int64

In [8]:
df.head(31)

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
0,2021-01-01 00:00:00,40.375568,-77.014318,5.136512,4.998009,5.927586,985.716862,4.951392,0.481294,0.761166,...,0.574400,0.777263,1.182116,0.502006,0.033843,0.978599,0.506152,0.885291,Moderate Risk,9.110682
1,2021-01-01 01:00:00,33.507818,-117.036902,5.101512,0.984929,1.591992,396.700206,1.030379,0.620780,0.196594,...,-9.753493,0.091839,9.611988,0.966774,0.201725,0.918586,0.980784,0.544178,High Risk,8.175281
2,2021-01-01 02:00:00,30.020640,-75.269224,5.090803,4.972665,8.787765,832.408935,4.220229,0.810933,0.152742,...,-6.491034,0.253529,6.570431,0.945627,0.264045,0.394215,0.998633,0.803322,High Risk,1.283594
3,2021-01-01 03:00:00,36.649223,-70.190529,8.219558,3.095064,0.045257,0.573283,0.530186,0.008525,0.811885,...,-0.151276,0.877576,0.548952,4.674035,0.362885,0.905444,0.993320,0.025977,High Risk,9.304897
4,2021-01-01 04:00:00,30.001279,-70.012195,5.000075,3.216077,8.004851,914.925067,3.620890,0.020083,0.053659,...,2.429448,0.262081,8.861443,3.445429,0.016957,0.258702,0.912433,0.991122,High Risk,7.752484
5,2021-01-01 05:00:00,47.864549,-119.998386,5.533563,4.862386,0.499405,822.590649,0.768521,0.062074,0.397323,...,11.301343,0.041378,9.492603,2.163846,0.183964,0.978620,0.838287,0.982023,High Risk,-1.630307
6,2021-01-01 06:00:00,33.846390,-95.940118,5.779804,4.999979,8.750501,6.048354,3.923828,0.333237,0.002689,...,-9.076670,0.243348,9.870430,4.159665,0.020699,0.986597,0.999357,0.061457,High Risk,5.135374
7,2021-01-01 07:00:00,32.601885,-102.316635,5.474695,0.375511,4.813078,256.293208,2.352963,0.021812,0.240859,...,36.838728,0.344496,2.954216,1.456898,0.012490,0.185078,0.514001,0.979538,Moderate Risk,7.432758
8,2021-01-01 08:00:00,39.787194,-90.897918,5.680607,4.958875,9.613161,109.816868,0.592249,0.049304,0.183048,...,-9.999960,0.914129,7.158868,2.169863,0.876879,0.996431,0.321267,0.223533,Moderate Risk,1.323351
9,2021-01-01 09:00:00,47.728499,-113.413561,5.088425,1.508709,9.897407,0.032110,0.781215,0.069873,0.744814,...,-10.000000,0.032444,3.587067,3.751473,0.011959,0.453395,0.996365,0.233778,High Risk,0.739935
10,2021-01-01 10:00:00,33.947731,-89.513347,6.601943,-0.063973,8.451799,146.129087,2.548538,0.343390,0.989638,...,26.218893,0.002587,1.472212,0.508620,0.026289,0.188894,0.962970,0.999999,High Risk,6.389037
11,2021-01-01 11:00:00,33.473813,-70.000603,5.015169,4.999792,0.254118,130.470997,0.694461,0.000603,0.867935,...,-2.369568,0.156763,9.999747,0.715279,0.942447,0.923544,0.992253,0.520720,High Risk,0.300676
12,2021-01-01 12:00:00,31.024236,-74.122162,9.190993,4.998451,1.114360,513.745302,4.712044,0.523023,0.597352,...,-9.598677,0.406688,8.416565,1.634058,0.272882,0.994091,0.870200,0.604883,High Risk,9.992329
13,2021-01-01 13:00:00,49.565253,-83.847535,5.378060,1.808200,6.229265,443.621487,1.427066,0.005191,0.838429,...,33.948500,0.000003,9.907507,0.501597,0.176164,0.999904,0.994860,0.772313,High Risk,9.490776
14,2021-01-01 14:00:00,46.916718,-78.800561,7.665823,4.639891,9.195519,24.651834,2.745088,0.336015,0.779954,...,-9.481047,0.263342,3.390479,0.502567,0.785134,0.935453,0.982630,0.977961,High Risk,7.926191
15,2021-01-01 15:00:00,30.023531,-113.544667,12.617927,4.303425,8.896589,370.537551,2.599165,0.395823,0.153994,...,19.618482,0.698205,8.988753,0.874239,0.935724,0.952611,0.822465,0.882029,High Risk,9.201606
16,2021-01-01 16:00:00,44.240019,-78.487059,5.138370,4.989709,5.372658,4.099028,2.871930,0.471894,0.535235,...,21.434622,0.790922,9.999335,4.240464,0.943185,0.793185,0.993119,0.876672,High Risk,9.861825
17,2021-01-01 17:00:00,42.065269,-100.541955,6.001007,4.994636,1.472932,55.211954,4.371112,0.286442,0.845134,...,-9.999998,0.135189,4.986957,3.232184,0.675503,0.513400,0.989862,0.997020,High Risk,-1.239944
18,2021-01-01 18:00:00,30.330197,-70.000960,5.000000,-0.346369,1.450323,18.922571,1.283073,0.224241,0.045559,...,8.099549,0.019594,9.720375,2.155055,0.689267,0.195046,0.917916,0.324167,High Risk,-0.687971
19,2021-01-01 19:00:00,30.005138,-94.513232,19.467032,4.563928,9.405084,232.677355,3.773324,0.620308,0.779766,...,-5.898583,0.018689,8.035104,0.651116,0.987247,0.998603,0.992198,0.720063,High Risk,8.111611
20,2021-01-01 20:00:00,31.267428,-71.484492,5.627314,-0.330389,6.782113,56.520383,4.322212,0.009437,0.869617,...,-2.916738,0.990056,8.645449,4.532008,0.000487,0.994946,0.387675,0.107617,Moderate Risk,8.949881
21,2021-01-01 21:00:00,32.777807,-81.749298,5.036266,-1.279526,0.138953,455.217808,0.501092,0.040018,0.739171,...,-8.491433,0.015895,4.865510,3.142306,0.708215,0.590239,1.000000,0.356868,High Risk,0.901131
22,2021-01-01 22:00:00,45.730328,-70.416504,5.001626,4.909054,6.524886,343.044554,4.658985,0.013477,0.945106,...,-9.705916,0.007151,5.157934,3.994555,0.499292,0.995134,0.999962,0.999807,High Risk,8.760505
23,2021-01-01 23:00:00,30.680607,-70.650922,5.965114,0.953610,3.929661,117.887817,1.694331,0.433239,0.998694,...,31.345144,0.009828,9.228818,2.743030,0.080654,0.689759,0.573940,0.945997,Moderate Risk,8.515220
24,2021-01-02 00:00:00,30.056376,-84.585329,5.555734,1.458750,6.059336,838.685512,1.767235,0.987785,0.642087,...,-5.844804,0.026304,9.486648,1.591359,0.588797,0.227769,0.999619,0.618584,High Risk,-0.425234
25,2021-01-02 01:00:00,39.059790,-97.937523,5.011879,4.864166,4.730473,61.651780,3.917735,0.263766,0.999889,...,14.546815,0.000054,2.046979,3.384156,0.096113,0.730927,0.999986,0.926330,High Risk,9.998838
26,2021-01-02 02:00:00,45.539837,-70.652467,5.000424,4.998603,6.578096,333.599976,3.872306,0.063573,0.999289,...,-9.909989,0.176554,5.418797,0.504834,0.038428,0.999506,0.831117,0.999783,High Risk,-1.131496
27,2021-01-02 03:00:00,32.076539,-76.828807,5.451173,4.885918,2.565735,61.455667,3.870085,0.001254,0.206940,...,-4.319054,0.175362,9.997401,3.510069,0.780802,0.955734,0.999981,0.999946,High Risk,7.545349
28,2021-01-02 04:00:00,30.212998,-84.309329,5.515055,4.028686,1.318352,992.364393,2.670531,0.000004,0.987475,...,14.416068,0.715700,9.649943,0.655774,0.058992,0.000184,0.610688,0.992899,Moderate Risk,0.374550
29,2021-01-02 05:00:00,30.030977,-96.004125,19.501174,3.427726,1.687176,20.538410,3.183966,0.182222,0.304452,...,-9.980334,0.566243,8.833063,0.587245,0.976661,0.546824,0.994827,0.920586,High Risk,8.059741
30,2021-01-02 06:00:00,47.712881,-70.812099,5.606163,3.735248,8.026608,349.316146,4.858963,0.072710,0.968566,...,-9.443323,0.087828,2.511618,0.880685,0.297614,0.780414,0.999705,0.538670,High Risk,9.486007

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.linear_model import LogisticRegression , LinearRegression
from sklearn.tree import DecisionTreeClassifier , DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier , RandomForestRegressor
from sklearn.svm import SVC , SVR
from sklearn.metrics import accuracy_score , mean_squared_error , r2_score , mean_absolute_error

In [10]:
# Prepare features and target variables for classification and regression tasks

X=df.drop(columns=['timestamp', 'risk_classification', 'delivery_time_deviation'])
y_clf=df['risk_classification']
y_reg=df['delivery_time_deviation']

In [11]:
#encoded categorical target variable for classification task
Le=LabelEncoder()
y_clf_encoded=Le.fit_transform(y_clf)

In [12]:
#scale numerical features for regression task
scalar=StandardScaler()
X_scaled=scalar.fit_transform(X)

In [13]:
#split the dataset into training and testing sets for classification task
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_scaled, y_clf_encoded, test_size=0.2, random_state=42)

In [14]:
#split the dataset into training and testing sets for regression task
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_scaled, y_reg, test_size=0.2, random_state=42)

In [15]:
#Classification Task
from sklearn.metrics import classification_report


print("---Classification Task---")
classification_models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Decision Tree Classifier': DecisionTreeClassifier(random_state=42),
    'Random Forest Classifier': RandomForestClassifier(random_state=42),
    'Support Vector Classifier': SVC(random_state=42)
}

for model_name, model in classification_models.items():
    print(f"\nTraining {model_name}...")
    model.fit(X_train_clf, y_train_clf)
    y_pred_clf = model.predict(X_test_clf)
    accuracy = accuracy_score(y_test_clf, y_pred_clf)
    print(f"{model_name} Accuracy: {accuracy:.4f}")
    print(f"{model_name} Classification Report for {model_name}:\n{classification_report(y_test_clf, y_pred_clf, target_names=Le.classes_)}")

---Classification Task---

Training Logistic Regression...
Logistic Regression Accuracy: 0.9983
Logistic Regression Classification Report for Logistic Regression:
               precision    recall  f1-score   support

    High Risk       1.00      1.00      1.00      4764
     Low Risk       1.00      0.99      0.99       641
Moderate Risk       0.99      1.00      0.99      1008

     accuracy                           1.00      6413
    macro avg       1.00      1.00      1.00      6413
 weighted avg       1.00      1.00      1.00      6413


Training Decision Tree Classifier...
Decision Tree Classifier Accuracy: 1.0000
Decision Tree Classifier Classification Report for Decision Tree Classifier:
               precision    recall  f1-score   support

    High Risk       1.00      1.00      1.00      4764
     Low Risk       1.00      1.00      1.00       641
Moderate Risk       1.00      1.00      1.00      1008

     accuracy                           1.00      6413
    macro avg       1.00      1.00      1.00      6413
 weighted avg       1.00      1.00      1.00      6413


Training Random Forest Classifier...
Random Forest Classifier Accuracy: 1.0000
Random Forest Classifier Classification Report for Random Forest Classifier:
               precision    recall  f1-score   support

    High Risk       1.00      1.00      1.00      4764
     Low Risk       1.00      1.00      1.00       641
Moderate Risk       1.00      1.00      1.00      1008

     accuracy                           1.00      6413
    macro avg       1.00      1.00      1.00      6413
 weighted avg       1.00      1.00      1.00      6413


Training Support Vector Classifier...
Support Vector Classifier Accuracy: 0.9871
Support Vector Classifier Classification Report for Support Vector Classifier:
               precision    recall  f1-score   support

    High Risk       0.99      0.99      0.99      4764
     Low Risk       0.97      0.97      0.97       641
Moderate Risk       0.96      0.96      0.96      1008

     accuracy                           0.99      6413
    macro avg       0.98      0.98      0.98      6413
 weighted avg       0.99      0.99      0.99      6413